export const cookies = [
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.696252,
        hostOnly: false,
        httpOnly: false,
        name: "__Secure-1PAPISID",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "YtQMcq6ssj2AFeeD/A-a6eGQ9pK0BYMtK1",
        id: 1,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.69661,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSID",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "g.a000ywiwtGr6Aj4o535UXQiBhrccA-rG-21bBRGTZaO7yaRXvUD2QYqh45qbQs1Fevq_yG_QvwACgYKAWgSARUSFQHGX2Mikv7ngox68WhehDCWXlyCGxoVAUF8yKpku-11jHLnREuwtwIvx7Hq0076",
        id: 2,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784336889.098758,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSIDCC",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "AKEyXzWq_KEiM69BPe6rFHSLt2tYKXij8NA7WcNcdNhZ35S5dIrKriuKkdjfZD7v1NwY7XmpzA",
        id: 3,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784336889.098645,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-1PSIDTS",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "sidts-CjIB5H03P_Yt1DZNqMB21h_DeeZQ_2sU38MqGEB4ciCPWBsA9RH86hCeEFb_TeESfdKH2hAA",
        id: 4,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.696301,
        hostOnly: false,
        httpOnly: false,
        name: "__Secure-3PAPISID",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "YtQMcq6ssj2AFeeD/A-a6eGQ9pK0BYMtK1",
        id: 5,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.696691,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSID",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "g.a000ywiwtGr6Aj4o535UXQiBhrccA-rG-21bBRGTZaO7yaRXvUD28DIg1mw08_YiiSWOXAtkcgACgYKAe4SARUSFQHGX2MiTH-RZvyEc_rzKMEAZL4WLhoVAUF8yKrDAoREDbVItry8SxHS6NOF0076",
        id: 6,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784336889.098781,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSIDCC",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "AKEyXzVqX_inWhegHGhEwt2uaEJHgFN864om7oUwhdBdRyEvOyGjKkt7S2xD19SNRnxlvLhKy1A",
        id: 7,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784336889.098702,
        hostOnly: false,
        httpOnly: true,
        name: "__Secure-3PSIDTS",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "sidts-CjIB5H03P_Yt1DZNqMB21h_DeeZQ_2sU38MqGEB4ciCPWBsA9RH86hCeEFb_TeESfdKH2hAA",
        id: 8,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.696125,
        hostOnly: false,
        httpOnly: false,
        name: "APISID",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "UqkWU4axXyjgUf9O/A6yB2haEDno9Bugj3",
        id: 9,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.695721,
        hostOnly: false,
        httpOnly: true,
        name: "HSID",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "AL5VGXNtKZEWq0dW4",
        id: 10,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1781154280.511797,
        hostOnly: false,
        httpOnly: true,
        name: "LOGIN_INFO",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "AFmmF2swRAIgbW6mZCn9WXl0Rn5Sq3Kw6_k4ufkdtGvCSMWxRCejO9UCIBH0N0MBEIgifFsfQNrXfyV1hVwm5MtwIBgP00YjtQ4r:QUQ3MjNmeW9aSUJuZ3h2NlFnZGhKTFN5UlkzZE9fV0xnNm1udW1iZHg1Z1h0dlNNWmQ3YTdGZ1Rvek9QeUh1UDJkV2dSejVQdk5FQmtjdXFYQ0VTQmtMcU4wZnBtUnZSZWpoSFMyU09JVGhBMkt1VXNNcjJQUTdETGlWUDZQM1BKODB2Z1ZXX2xxUzNZcU5DVzFCeFlzY01Hd082djFfb09B",
        id: 11,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1768550314.845444,
        hostOnly: false,
        httpOnly: true,
        name: "NID",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "525=UQ3wIVJL4m_VVwJb2y9_fFyO3I_EnB0dJl2VUaPubnh-QEdD4IAO7uVBY_IBQ1SUXy4jXaelBTbEi17aargfz3hr2BOluUtTFizCwrw9cooWlzc0nKeNA0qcXLEvkQ0NvQpoE8g75orBZSLSIkWGfFBCZwktJ6wDEt_DnS9YMSur1AcFVvq53YyzT4v378s8ZpPpCSYEkhA6AluNNMiVZWXIFsxIkA",
        id: 12,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1787304109.338805,
        hostOnly: false,
        httpOnly: false,
        name: "PREF",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "tz=Asia.Taipei",
        id: 13,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.696192,
        hostOnly: false,
        httpOnly: false,
        name: "SAPISID",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "YtQMcq6ssj2AFeeD/A-a6eGQ9pK0BYMtK1",
        id: 14,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.69656,
        hostOnly: false,
        httpOnly: false,
        name: "SID",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "g.a000ywiwtGr6Aj4o535UXQiBhrccA-rG-21bBRGTZaO7yaRXvUD21crVkDxyrsnCml7mQj9VdwACgYKAa0SARUSFQHGX2Miwni3oV6ThrvRt5WO0W62wxoVAUF8yKqBeOmWCx0v6nNDgnjKCata0076",
        id: 15,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1784336889.098734,
        hostOnly: false,
        httpOnly: false,
        name: "SIDCC",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "AKEyXzX03UB40AA6HUfXIa1sCCLRZzTBf6sY9LQRSv2XXTDpFhTibxyUwbd9UAfzdAnJRqn-H4w",
        id: 16,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1786168194.695961,
        hostOnly: false,
        httpOnly: true,
        name: "SSID",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "Ahee-uXpbC109Ei4G",
        id: 17,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1763523562.285318,
        hostOnly: false,
        httpOnly: true,
        name: "VISITOR_INFO1_LIVE",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "vs3tPtqoJfg",
        id: 18,
    },
    {
        domain: ".youtube.com",
        expirationDate: 1763523562.285388,
        hostOnly: false,
        httpOnly: true,
        name: "VISITOR_PRIVACY_METADATA",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "CgJUVxIEGgAgbg%3D%3D",
        id: 19,
    },
    {
        domain: "www.youtube.com",
        expirationDate: 1755331114,
        hostOnly: true,
        httpOnly: false,
        name: "OTZ",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "8173919_24_24__24_",
        id: 20,
    },
];
